### ISSUE TITLE
Market research Next.js v15 and libraries

### ISSUE THREAD

**Issue by Memetelve** [projekt-zespolowy-ug/P.Y.T.A#1]
<sub><a href="https://huly.app/guest/pyta?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFiZTU2ZGYwMmQ4YTAzZmIzM2RiYjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbWVtZXRlbHZlLXB5dGEtNjcwYzBkMWItY2Y5ZTE4MDAyYS00NDk4ZGIifQ.eF9fDhGb15TNmVbZFBeN7dCvh6mun3-jumcij4bVvjs">Huly&reg;: <b>PYTA-1</b></a></sub>

**Comment by olszewskista** [comment]
No problem found 😊

**Comment by olszewskista** [comment]
Task closed

**Comment by olszewskista** [comment]
dzieki

**Comment by mateusz-kurowskiUG** [comment]
* Shadcn

**Comment by mateusz-kurowskiUG** [comment]
* shadcn
* react-hook-form
* zustand
* react-query
*
