### ISSUE TITLE
Fire our scrum master cuz he's useless and lazy

### ISSUE THREAD

**Issue by mateusz-kurowskiUG** [projekt-zespolowy-ug/P.Y.T.A#21]
<sub><a href="https://huly.app/guest/pyta?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI2OTE3NTI3Y2M3NjgxYzYyNjA2MTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbWVtZXRlbHZlLXB5dGEtNjcwYzBkMWItY2Y5ZTE4MDAyYS00NDk4ZGIifQ.H2-EVWoaPD-a0rXTMC6ckGqEfsBDHZ38NFiLADtv1Ic">Huly&reg;: <b>PYTA-21</b></a></sub>

**Comment by olszewskista** [comment]
aha
