### ISSUE TITLE
Change discord status

### ISSUE THREAD

**Issue by olszewskista** [projekt-zespolowy-ug/P.Y.T.A#43]
Change your discord status to a normal one instead of trying to be invisible.

<sub><a href="https://huly.app/guest/pyta?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMzZTk0M2U3Y2M1YTc4NTQyYmYwZDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbWVtZXRlbHZlLXB5dGEtNjcwYzBkMWItY2Y5ZTE4MDAyYS00NDk4ZGIifQ.yg8zxE589-roP7LdkQD3gnNohmVyF9XxtfxzP-4Ufkw">Huly&reg;: <b>PYTA-43</b></a></sub>

**Comment by mateusz-kurowskiUG** [comment]
What if he's currently sleeping?
