### ISSUE TITLE
Create header for root layout

### ISSUE THREAD

**Issue by olszewskista** [projekt-zespolowy-ug/P.Y.T.A#59]
@Acceptance criteria:

* P.Y.T.A. logo to the left side
* Tabs to the left:
  * Store/Browse stocks
  * Portfolio
* Tabs to the right:
  * 
    * If logged out - log in button, locale switch, mode toggler, 
    * If logged in - language and dark-mode switch, <ins>balance</ins>, <ins>user photo</ins> and <ins>name</ins> -  drop-down on ~~hover~~ click (pozdro tymczasowo przynajmniej ~mk):
      * account details/settings
    *  log out button

<sub><a href="https://huly.app/guest/pyta?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzODRiY2QyZWY0Y2JjYzQ2ODc3ZDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbWVtZXRlbHZlLXB5dGEtNjcwYzBkMWItY2Y5ZTE4MDAyYS00NDk4ZGIifQ.Iw84orQlj6Xsb94sNcrtoMrkGwuEVXir1-5oWynQUK0">Huly&reg;: <b>PYTA-59</b></a></sub>

**Comment by Memetelve** [comment]
user photo url should be constructed like `https://www.gravatar.com/avatar/${hashed_email}?d=${our_style_choice}`. 

Possible styles (TBD):"
